Repository octokit/graphql-action, pull requests merged in 2020-05, with the labels that each got.

#17 feat: support mediaType parameter for API previews
  .github/workflows/test.yml
  dist/index.js
  index.js
  package-lock.json
  package.json
Labels: feature

#19 Replace Greenkeeper with Dependabot
  .github/dependabot.yml
  README.md
Labels: maintenance

#27 fix: do not YAML-parse the `query` input
  index.js
Labels: bug
